name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - LICENSE
      - .github/FUNDING.yml
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing pip dependencies
        run: python -m pip install --upgrade pip clickgen
        continue-on-error: false

      # https://github.com/returntocorp/semgrep/issues/4794
      - name: Fixing 'attr' module error
        run: pip install --force-reinstall --upgrade attrs

      - name: Building `Fuchsia` Cursors
        run: ctgen build.toml -d 'bitmaps/Fuchsia' -n 'Fuchsia' -c 'Fuchsia cursors.'

      - name: Building `Fuchsia Pop` Cursors
        run: ctgen build.toml -d 'bitmaps/Fuchsia-Pop' -n 'Fuchsia-Pop' -c 'Fuchsia Pop! cursors.'

      - name: Building `Fuchsia Red` Cursors
        run: ctgen build.toml -d 'bitmaps/Fuchsia-Red' -n 'Fuchsia-Red' -c 'Fuchsia Red cursors.'
        run: ctgen build.toml -d 'bitmaps/BreezeX-Black' -n 'BreezeX-Black' -c 'BreezeX Black cursors.'
