name: build

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
    branches: [main, dev]
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.bbcode"
      - LICENSE
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install build dependencies (apt)
        run: sudo apt install -y libx11-dev libxcursor-dev libpng-dev
        continue-on-error: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Caching yarn packages
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set Up NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Caching pip packages
        uses: actions/cache@v2
        id: pip-cache # use this to check for `cache-hit` (`steps.pip-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Generating `Fuchsia` Cursor Theme
        run: make
        continue-on-error: false

      - name: Compressing UNIX theme
        run: |
          tar -cvzf Fuchsia.tar.gz themes/Fuchsia
          tar -cvzf Fuchsia-Pop!.tar.gz themes/Fuchsia-Pop!
          tar -cvzf Fuchsia-Red.tar.gz themes/Fuchsia-Red

      - name: Uploading `bitmaps` artifact
        uses: actions/upload-artifact@v2
        with:
          name: bitmaps
          path: bitmaps/*

      - name: Uploading `Fuchsia` UNIX Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Fuchsia
          path: Fuchsia.tar.gz

      - name: Uploading `Fuchsia-Pop!` UNIX Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Fuchsia-Pop!
          path: Fuchsia-Pop!.tar.gz

      - name: Uploading `Fuchsia-Red` UNIX Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Fuchsia-Red
          path: Fuchsia-Red.tar.gz

      - name: Uploading `Fuchsia` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Fuchsia-Windows
          path: themes/Fuchsia-Windows/*

      - name: Uploading `Fuchsia-Pop!` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Fuchsia-Pop!-Windows
          path: themes/Fuchsia-Pop!-Windows/*

      - name: Uploading `Fuchsia-Red` Windows Theme artifact
        uses: actions/upload-artifact@v2
        with:
          name: Fuchsia-Red-Windows
          path: themes/Fuchsia-Red-Windows/*
